"""Database setup

Revision ID: 61e62b8b58de
Revises: 
Create Date: 2024-09-01 17:20:10.445304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e62b8b58de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_users',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('omniban', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_user_id', 'telegram_chat_id')
    )
    op.create_index(op.f('ix_banned_users_telegram_chat_id'), 'banned_users', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_banned_users_telegram_user_id'), 'banned_users', ['telegram_user_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('added_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_telegram_chat_id'), 'chats', ['telegram_chat_id'], unique=True)
    op.create_table('nlp_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nlp_questions_message_id'), 'nlp_questions', ['message_id'], unique=False)
    op.create_index(op.f('ix_nlp_questions_user_id'), 'nlp_questions', ['user_id'], unique=False)
    op.create_table('persistent_settings',
    sa.Column('setting_name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('setting_name')
    )
    op.create_table('users',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BANNED', name='status'), server_default='ACTIVE', nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MASTER', name='role'), nullable=True),
    sa.PrimaryKeyConstraint('telegram_user_id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('raw_data', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['nlp_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_question_id'), 'feedbacks', ['question_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_value'), 'feedbacks', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_value'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_question_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_table('persistent_settings')
    op.drop_index(op.f('ix_nlp_questions_user_id'), table_name='nlp_questions')
    op.drop_index(op.f('ix_nlp_questions_message_id'), table_name='nlp_questions')
    op.drop_table('nlp_questions')
    op.drop_index(op.f('ix_chats_telegram_chat_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_banned_users_telegram_user_id'), table_name='banned_users')
    op.drop_index(op.f('ix_banned_users_telegram_chat_id'), table_name='banned_users')
    op.drop_table('banned_users')
    # ### end Alembic commands ###
